name: CI

on: [push, pull_request]

jobs:
  style:
    name: Check style conventions
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Setup the checking tools
        run: pip install -r dev-requirements.txt
      - name: Test the package style conventions
        run: make check
